Update RNInstallReferrerClient.java
When we use react-native-device-info in Electrode native project, there is an error during container compiling:
 
:heavy_multiplication_x: An error occurred: Command failed: ./gradlew lib:uploadArchives
:heavy_multiplication_x: /private/var/folders/kc/hj8kf3gd5w55_39001pwxy9m0000gp/T/tmp-494366bW875QsqbOB/lib/src/main/java/com/learnium/RNDeviceInfo/RNInstallReferrerClient.java:78: error: cannot find symbol
:heavy_multiplication_x:     if (BuildConfig.DEBUG) Log.d(“RNInstallReferrerClient”, “InstallReferrerService disconnected”);


The reason is BuildConfig was generated in the package: com.walmartlabs.ern.container

For this, could you please comment out those BuildConfig.DEBUG lines,  if you need to, probably better to specify the class package.

Thanks